---
- name: "Generate Directories"
  file:
    path: "{{ item }}"
    owner: "root"
    group: "bind"
    state: directory
    mode: 0775
  become: yes
  with_items:
    - "/etc/bind/zones"
    - "/etc/bind/zones/{{ network.domain }}"

- name: "Copy zone-files to host"
  copy:
    src:   "{{ inventory_dir }}/dynamic_vars/files/config/dns/zone-file/{{ item.domain }}.zone"
    dest:  "/etc/bind/zones/{{ network.domain }}/{{ item.domain }}.zone"
    owner: "root"
    group: "bind"
    mode:  0664
  become:  true 
  with_items:
    - "{{ domain_files }}"
  notify: restart bind9-daemon

- name: "Copy reverse-zone-files to host"
  copy:
    src:   "{{ inventory_dir }}/dynamic_vars/files/config/dns/zone-file/{{ item }}.in-addr.arpa.zone"
    dest:  "/etc/bind/zones/{{ network.domain }}/{{ item }}.in-addr.arpa.zone"
    owner: "root"
    group: "bind"
    mode:  0664
  become: true 
  with_items:
    - "{{ reverse_domain_files }}"
  notify: restart bind9-daemon

- name: Generate /etc/bind/named.conf.local
  template:
    src: "named.conf.local.j2"
    dest: "/etc/bind/named.conf.local"
    owner: "root"
    group: "bind"
    mode: 0644
  become: yes 
  notify: restart bind9-daemon

- name: Generate /etc/bind/named.conf.options
  template:
    src: "named.conf.options.j2"
    dest: "/etc/bind/named.conf.options"
    owner: "root"
    group: "bind"
    mode: 0644
  become: yes   
  notify: restart bind9-daemon
  