---
- name: Install bind9-Package
  apt:
    name: [ "bind9", "bind9utils", "bind9-doc", "dnsutils" ]
    state: present
    update_cache:     "{{ apt_proxy.update_repo | default(no) }}"
    cache_valid_time: "{{ apt_proxy.update_cache | default(0) }}"
  become: yes